# Generated by Django 5.0.3 on 2024-03-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App_Blog", "0002_alter_blog_options_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blog_image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images"),
        ),
    ]
