# Generated by Django 5.0.3 on 2024-03-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App_Blog", "0004_alter_blog_blog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blog_image",
            field=models.ImageField(upload_to="blog_images"),
        ),
    ]
