# Generated by Django 5.0.3 on 2024-03-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App_Blog", "0007_alter_blog_blog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(max_length=264, null=True, unique=True),
        ),
    ]
